"""MoreyMachine Streamlit product UI.

The app is intentionally artifact-first: it reads cached Parquet, JSON, and
Markdown files generated by the offline pipeline. It never fetches NBA data in a
page load and it never falls back to demo data in real mode.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st

from moreymachine.app import ui
from moreymachine.app.data_sources import REGISTRY_BY_KEY, data_source_table
from moreymachine.app.loaders import (
    get_missing_artifact_message,
    get_team_output_dir,
    load_available_teams,
)
from moreymachine.app.state import (
    SELECTED_BENCHMARK_KEY,
    SELECTED_PLAYER_ID_KEY,
    SELECTED_TEAM_KEY,
)
from moreymachine.config.teams import SUPPORTED_TEAM_ABBRS, normalize_team, team_name
from moreymachine.data.freshness import REFRESH_COMMAND
from moreymachine.models.best_by_need import BEST_BY_NEED_PATH
from moreymachine.models.explanation_engine_v2 import (
    EVIDENCE_OBJECTS_PATH,
    EXPLANATION_CLAIMS_PATH,
)
from moreymachine.models.fit_breakdown import PLAYER_FIT_BREAKDOWNS_PATH
from moreymachine.models.help_impact import PLAYER_HELP_IMPACT_PATH
from moreymachine.models.player_profile_builder import (
    PLAYER_PROFILES_PATH,
)
from moreymachine.models.recommendation_engine_v2 import (
    CANDIDATE_FIT_RANKINGS_V2_PATH,
)
from moreymachine.models.scenario_engine import CANDIDATE_SCENARIOS_PATH
from moreymachine.utils.paths import (
    FEATURES_DATA_DIR,
    PROCESSED_DATA_DIR,
    REPORTS_DATA_DIR,
    TRANSACTIONS_PATH,
)
from moreymachine.utils.real_data import is_demo_path

ROSTER_WORLD_PATH = PROCESSED_DATA_DIR / "roster_world_phi.parquet"
CONTENDER_BLUEPRINTS_PATH = FEATURES_DATA_DIR / "contender_blueprints.parquet"
TEAM_ARCHETYPES_PATH = FEATURES_DATA_DIR / "team_construction_archetypes.parquet"
GAP_MODEL_PATH = FEATURES_DATA_DIR / "sixers_gap_model.parquet"
SKILL_PROFILES_PATH = FEATURES_DATA_DIR / "player_skill_profiles.parquet"
COMPATIBILITY_PATH = FEATURES_DATA_DIR / "candidate_core_compatibility.parquet"
ROSTER_SIMULATION_PATH = FEATURES_DATA_DIR / "candidate_roster_simulation.parquet"
PLAYER_CATEGORIZATIONS_PATH = FEATURES_DATA_DIR / "player_categorizations.parquet"
CANDIDATE_UNIVERSE_PATH = FEATURES_DATA_DIR / "candidate_universe.parquet"
REASONING_VALIDATION_PATH = REPORTS_DATA_DIR / "reasoning_validation_v2.md"
PROFILE_VALIDATION_PATH = REPORTS_DATA_DIR / "player_profile_validation.md"
SCHEMA_VALIDATION_PATH = REPORTS_DATA_DIR / "schema_validation.md"
BACKTEST_SUMMARY_PATH = REPORTS_DATA_DIR / "backtest_summary.md"
BACKTEST_RESULTS_PATH = REPORTS_DATA_DIR / "backtest_results.json"

BOARD_COLUMNS = (
    "player_id",
    "rank",
    "player_name",
    "current_team",
    "position",
    "candidate_type",
    "board_type",
    "recommendation",
    "final_recommendation_score",
    "recommendation_confidence",
    "primary_roster_slot",
    "expected_role_on_phi",
    "expected_minutes_context",
    "starter_possible",
    "closing_possible",
    "playoff_rotation_possible",
    "acquisition_path",
    "acquisition_feasibility_score",
    "contract_value_score",
    "risk_score",
    "opportunity_cost_score",
    "gaps_addressed",
    "gaps_not_addressed",
    "compatibility_with_embiid",
    "compatibility_with_maxey",
    "compatibility_with_george",
    "manual_review_required",
    "missing_data_flags",
)


def main() -> None:
    """Run the Streamlit app.

    Navigation follows the GM's actual workflow: read the team, decide on moves,
    research players, run front-office ops, then check the model's own trust
    record. The sidebar carries the team selector and live artifact status.
    """
    st.set_page_config(
        page_title="MoreyMachine — GM War Room",
        page_icon="🏀",
        layout="wide",
        initial_sidebar_state="expanded",
    )
    ui.inject_theme()
    _sidebar_brand()
    _sidebar_team_controls()

    nav = st.navigation(
        {
            "War Room": [
                st.Page(render_war_room, title="Command Center", icon=":material/dashboard:", default=True),
            ],
            "Team Read": [
                st.Page(render_roster_lab, title="Roster & Depth Chart", icon=":material/groups:"),
                st.Page(render_team_level, title="Team Level", icon=":material/speed:"),
                st.Page(render_benchmark_path, title="Benchmark Path", icon=":material/timeline:"),
                st.Page(render_gap_model, title="Gap Priority Model", icon=":material/crisis_alert:"),
                st.Page(render_blueprints, title="Contender Blueprints", icon=":material/architecture:"),
            ],
            "Decisions": [
                st.Page(render_move_recommendations, title="Move Recommendations", icon=":material/swap_horiz:"),
                st.Page(render_target_board, title="Target Board", icon=":material/list_alt:"),
                st.Page(render_best_by_need, title="Best By Need", icon=":material/search:"),
                st.Page(render_move_compare, title="Move Compare", icon=":material/compare_arrows:"),
            ],
            "Player Research": [
                st.Page(render_player_detail, title="Player Detail", icon=":material/person:"),
                st.Page(render_player_compare, title="Player Compare", icon=":material/compare:"),
                st.Page(render_skill_profiles, title="Skill Profiles", icon=":material/insights:"),
                st.Page(render_compatibility, title="Core Compatibility", icon=":material/hub:"),
                st.Page(render_roster_simulation, title="Roster Slot Simulation", icon=":material/dynamic_feed:"),
                st.Page(render_scenarios, title="Candidate Scenarios", icon=":material/alt_route:"),
            ],
            "Front Office Ops": [
                st.Page(render_transaction_review, title="Transaction Review", icon=":material/receipt_long:"),
                st.Page(render_manual_review_queue, title="Manual Review Queue", icon=":material/flag:"),
                st.Page(render_data_sources, title="Data Sources & Freshness", icon=":material/database:"),
                st.Page(render_team_selector, title="Analyze Any Team", icon=":material/groups_2:"),
            ],
            "Trust & Method": [
                st.Page(render_reasoning_diagnostics, title="Reasoning Diagnostics", icon=":material/fact_check:"),
                st.Page(render_backtest, title="Backtest Proof", icon=":material/history:"),
                st.Page(render_limitations, title="Limitations", icon=":material/warning:"),
                st.Page(render_product_summary, title="How It Reasons", icon=":material/menu_book:"),
            ],
        }
    )
    _sidebar_status()
    nav.run()


def _sidebar_brand() -> None:
    """Render the product mark at the top of the nav rail."""
    st.sidebar.markdown(
        '<div style="font-family:Archivo,sans-serif;font-weight:800;font-size:1.3rem;'
        'letter-spacing:-0.01em;color:#fff;line-height:1;">MOREY<span style="color:#C9872E;">MACHINE</span></div>'
        '<div style="font-size:0.7rem;letter-spacing:0.14em;text-transform:uppercase;'
        'color:#8FA4BC;margin:4px 0 6px;">GM War Room</div>',
        unsafe_allow_html=True,
    )


@st.cache_data(show_spinner=False)
def _read_frame(path_string: str, mtime: float) -> pd.DataFrame:
    path = Path(path_string)
    if path.suffix == ".csv":
        return pd.read_csv(path)
    return pd.read_parquet(path)


@st.cache_data(show_spinner=False)
def _read_json(path_string: str, mtime: float) -> Any:
    return json.loads(Path(path_string).read_text(encoding="utf-8"))


@st.cache_data(show_spinner=False)
def _read_text(path_string: str, mtime: float) -> str:
    return Path(path_string).read_text(encoding="utf-8")


def frame(path: Path, label: str, command: str) -> pd.DataFrame:
    """Load a cached data artifact or render an exact recovery command."""
    if is_demo_path(path):
        st.error(f"{label} points at demo data and cannot be used in real mode.")
        return pd.DataFrame()
    if not path.exists():
        st.error(f"Missing required artifact: `{path}`")
        st.code(command, language="bash")
        return pd.DataFrame()
    return _read_frame(str(path), path.stat().st_mtime)


def load(key: str) -> pd.DataFrame:
    """Compatibility loader for registered real datasets."""
    dataset = REGISTRY_BY_KEY[key]
    if is_demo_path(dataset.path) or not dataset.path.exists():
        return pd.DataFrame()
    return _read_frame(str(dataset.path), dataset.path.stat().st_mtime)


def json_artifact(path: Path, label: str, command: str) -> Any:
    """Load a cached JSON artifact or render an exact recovery command."""
    if not path.exists():
        st.error(f"Missing required artifact: `{path}`")
        st.code(command, language="bash")
        return None
    return _read_json(str(path), path.stat().st_mtime)


def text_artifact(path: Path) -> str:
    """Load optional Markdown/text output."""
    if not path.exists():
        return ""
    return _read_text(str(path), path.stat().st_mtime)


def selected_team() -> str:
    """Return the selected team abbreviation."""
    return normalize_team(st.session_state.get(SELECTED_TEAM_KEY, "PHI"))


def team_artifact_path(relative_path: str) -> Path:
    """Return a team-scoped artifact path."""
    return get_team_output_dir(selected_team()) / relative_path


def team_frame(
    relative_path: str,
    fallback_path: Path,
    label: str,
    command: str,
) -> pd.DataFrame:
    """Load team-scoped artifact, falling back to the legacy global PHI artifact."""
    path = team_artifact_path(relative_path)
    if path.exists():
        return frame(path, label, command)
    if selected_team() == "PHI":
        return frame(fallback_path, label, command)
    st.error(f"Missing required artifact: `{path}`")
    st.code(command, language="bash")
    return pd.DataFrame()


def team_json(relative_path: str, fallback_path: Path | None = None) -> Any:
    """Load team-scoped JSON with optional global fallback."""
    path = team_artifact_path(relative_path)
    if path.exists():
        return _read_json(str(path), path.stat().st_mtime)
    if selected_team() == "PHI" and fallback_path and fallback_path.exists():
        return _read_json(str(fallback_path), fallback_path.stat().st_mtime)
    return None


def team_text(relative_path: str, fallback_path: Path | None = None) -> str:
    """Load team-scoped Markdown/text with optional global fallback."""
    path = team_artifact_path(relative_path)
    if path.exists():
        return _read_text(str(path), path.stat().st_mtime)
    if selected_team() == "PHI" and fallback_path and fallback_path.exists():
        return text_artifact(fallback_path)
    return ""


def _safe_widget_key(text: str) -> str:
    return (
        str(text)
        .lower()
        .strip()
        .replace(" ", "*")
        .replace("/", "*")
        .replace("-", "*")
        .replace("(", "")
        .replace(")", "")
        .replace(".", "")
        .replace(":", "")
        .replace("|", "_")
    )


def render_war_room() -> None:
    """Render the command-center home: status, do-first moves, gaps, benchmark."""
    team = selected_team()
    team_level = team_json("reports/team_level.json", REPORTS_DATA_DIR / "team_level.json") or {}
    action_cards = team_json("reports/action_cards.json", REPORTS_DATA_DIR / "action_cards.json") or []
    narrative = team_text("narratives/gm_executive_summary.md")
    rankings = rankings_frame()

    if not team_level and not action_cards:
        st.title(f"{team_name(team)} — Command Center")
        st.warning(get_missing_artifact_message(team))
        st.code(_run_command(team), language="bash")
        return

    ui.status_band(
        team_name(team),
        level=team_level.get("team_level", "Unknown"),
        score=team_level.get("level_score", "—"),
        percentile=team_level.get("contender_percentile", "—"),
        archetype=team_level.get("closest_archetype", "—"),
        season=team_level.get("season", "—"),
    )

    strong_fits = (
        int((rankings["recommendation"] == "Strong Fit If Affordable").sum())
        if not rankings.empty
        else 0
    )
    manual = (
        int(rankings.get("manual_review_required", pd.Series(dtype=bool)).sum())
        if not rankings.empty
        else 0
    )
    high_priority_moves = sum(1 for c in action_cards if str(c.get("priority", "")).lower() == "high")
    ui.scoreboard(
        [
            {"label": "Team Level", "value": team_level.get("team_level", "—"), "sub": f"score {team_level.get('level_score', '—')}"},
            {"label": "Contender %ile", "value": team_level.get("contender_percentile", "—"), "accent": "amber", "sub": "vs league field"},
            {"label": "Strong Fits", "value": strong_fits, "accent": "green", "sub": "if affordable"},
            {"label": "Priority Moves", "value": high_priority_moves, "accent": "amber", "sub": "high priority cards"},
            {"label": "Manual Review", "value": manual, "accent": "red" if manual else "slate", "sub": "needs verification"},
        ]
    )

    left, right = st.columns([3, 2], gap="large")

    with left:
        ui.eyebrow("Do First — Top Moves on the Board")
        do_first = [
            c
            for c in action_cards
            if c.get("action_category")
            in ("best_overall_action", "best_realistic_free_agent", "best_realistic_trade")
        ] or action_cards[:3]
        for card in do_first[:3]:
            ui.decision_card(card)

        avoid = next((c for c in action_cards if c.get("action_category") == "top_avoid_move"), None)
        if avoid:
            ui.eyebrow("Do Not Do This")
            ui.decision_card(avoid)

    with right:
        ui.eyebrow("Biggest Roster Gaps")
        gaps = team_frame(
            "features/gap_model.parquet", GAP_MODEL_PATH, "Gap priority model", _run_command(team)
        )
        if not gaps.empty and "severity" in gaps.columns:
            top_gaps = gaps.copy()
            top_gaps["severity_num"] = pd.to_numeric(top_gaps["severity"], errors="coerce").fillna(0)
            top_gaps = top_gaps.sort_values("severity_num", ascending=False).head(6)
            max_sev = max(float(top_gaps["severity_num"].max()), 1.0)
            for _, row in top_gaps.iterrows():
                sev = float(row["severity_num"])
                ui.stat_bar(
                    str(row.get("gap_name", "Gap")),
                    sev,
                    max_value=max_sev,
                    kind=ui.severity_kind(sev, hi=max_sev * 0.66, mid=max_sev * 0.33),
                    right=f"{sev:.0f}",
                )
        else:
            st.info("No gap model loaded.")

        ui.eyebrow("Closest Benchmark")
        comparison = team_frame(
            "reports/team_comparison.parquet",
            REPORTS_DATA_DIR / "team_comparison.parquet",
            "Team comparison",
            _run_command(team),
        )
        if not comparison.empty:
            _benchmark_snapshot(comparison, team_level.get("closest_archetype"))

    if narrative:
        ui.eyebrow("GM Read")
        ui.note(narrative)


def _benchmark_snapshot(comparison: pd.DataFrame, closest: Any) -> None:
    """Render gap bars for the closest benchmark on the home page."""
    row = None
    if closest:
        match = comparison[comparison["benchmark"].astype(str) == str(closest)]
        if not match.empty:
            row = match.iloc[0]
    if row is None:
        row = comparison.iloc[0]
    st.caption(f"Gap to **{row.get('benchmark', 'benchmark')}** (higher bar = further away)")
    dims = [
        ("Net rating", "net_rating_gap"),
        ("Offense", "offense_gap"),
        ("Defense", "defense_gap"),
        ("Shooting", "shooting_gap"),
        ("Two-way", "two_way_gap"),
    ]
    values = [abs(float(row[col])) for _, col in dims if col in row and pd.notna(row[col])]
    max_gap = max(values + [1.0])
    for label, col in dims:
        if col in row and pd.notna(row[col]):
            gap = abs(float(row[col]))
            ui.stat_bar(
                label,
                gap,
                max_value=max_gap,
                kind=ui.severity_kind(gap, hi=max_gap * 0.66, mid=max_gap * 0.33),
                right=f"{float(row[col]):+.1f}",
            )


def render_team_selector() -> None:
    """Render team selection and analysis command."""
    team = selected_team()
    st.title("Team Selector / Analyze Any Team")
    st.metric("Selected team", f"{team} - {team_name(team)}")
    root = get_team_output_dir(team)
    st.write(f"Output directory: `{root}`")
    st.code(_run_command(team), language="bash")
    artifacts = _team_artifact_status(team)
    st.dataframe(pd.DataFrame(artifacts), use_container_width=True, hide_index=True)


def render_team_level() -> None:
    """Render team-level diagnosis."""
    team = selected_team()
    st.title(f"{team_name(team)} — Team Level")
    payload = team_json("reports/team_level.json", REPORTS_DATA_DIR / "team_level.json") or {}
    if not payload:
        st.warning(get_missing_artifact_message(team))
        st.code(_run_command(team), language="bash")
        return
    ui.scoreboard(
        [
            {"label": "Current Level", "value": payload.get("team_level", "—")},
            {"label": "Level Score", "value": payload.get("level_score", "—"), "accent": "amber"},
            {"label": "Contender %ile", "value": payload.get("contender_percentile", "—"), "accent": "amber"},
            {"label": "Confidence", "value": str(payload.get("confidence", "—")).title(), "accent": "slate"},
        ]
    )
    left, right = st.columns(2, gap="large")
    with left:
        ui.eyebrow("Strengths")
        for item in payload.get("main_strengths", []) or ["No clear above-median strength signal."]:
            st.markdown(f"- {item}")
        ui.eyebrow("Why This Level")
        for item in _json_list(payload.get("why_this_level")):
            st.markdown(f"- {item}")
    with right:
        ui.eyebrow("Weaknesses")
        for item in payload.get("main_weaknesses", []) or ["—"]:
            st.markdown(f"- {item}")
        ui.eyebrow("What The Next Level Requires")
        for item in _json_list(payload.get("what_level_requires_next")):
            st.markdown(f"- {item}")
    ui.eyebrow("Evidence")
    st.write(payload.get("evidence", []))
    flags = payload.get("missing_data_flags", [])
    if flags:
        ui.eyebrow("Missing Data Flags")
        st.write(flags)


def render_benchmark_path() -> None:
    """Render benchmark comparison path."""
    team = selected_team()
    st.title(f"{team_name(team)} — Benchmark Path")
    st.caption("How far the team sits from contender reference groups, dimension by dimension.")
    level = team_json("reports/team_level.json", REPORTS_DATA_DIR / "team_level.json") or {}
    comparison = team_frame(
        "reports/team_comparison.parquet",
        REPORTS_DATA_DIR / "team_comparison.parquet",
        "Team comparison",
        _run_command(team),
    )
    if comparison.empty:
        return
    benchmarks = comparison["benchmark"].dropna().astype(str).tolist()
    benchmark_path_key = "benchmark_path_select"
    sidebar_benchmark = st.session_state.get(SELECTED_BENCHMARK_KEY)
    closest = str(level.get("closest_archetype")) if level else None
    default_benchmark = (
        sidebar_benchmark
        if sidebar_benchmark in benchmarks
        else (closest if closest in benchmarks else benchmarks[0])
    )
    if st.session_state.get(benchmark_path_key) not in benchmarks:
        st.session_state[benchmark_path_key] = default_benchmark
    selected = st.selectbox("Benchmark", benchmarks, key=benchmark_path_key)
    row = comparison[comparison["benchmark"].astype(str) == selected].iloc[0]

    ui.scoreboard(
        [
            {"label": "Benchmark", "value": selected},
            {"label": "Overall Gap", "value": _fmt_num(row.get("overall_gap_score")), "accent": "amber"},
            {"label": "Net Rating Gap", "value": _fmt_num(row.get("net_rating_gap")), "accent": "red"},
            {"label": "Confidence", "value": str(row.get("confidence", "—")).title(), "accent": "slate"},
        ]
    )
    ui.eyebrow("Distance by Dimension")
    _benchmark_snapshot(comparison, selected)
    if row.get("why_it_matters"):
        ui.note(f"<p><b>Why it matters.</b> {ui._h(row.get('why_it_matters'))}</p>")
    ui.eyebrow("All Benchmarks")
    st.dataframe(comparison, use_container_width=True, hide_index=True)


def _fmt_num(value: Any) -> str:
    try:
        return f"{float(value):.1f}"
    except (TypeError, ValueError):
        return "—"


def render_move_recommendations() -> None:
    """Render action-card-first move recommendations."""
    team = selected_team()
    st.title(f"{team_name(team)} — Move Recommendations")
    st.caption("Each card is a decision, not a ranking row: what to do, why, and what would make it wrong.")
    cards = team_json("reports/action_cards.json", REPORTS_DATA_DIR / "action_cards.json") or []
    moves = team_frame(
        "reports/move_recommendations.parquet",
        REPORTS_DATA_DIR / "move_recommendations.parquet",
        "Move recommendations",
        _run_command(team),
    )
    if cards:
        ui.eyebrow("GM Action Cards")
        positive = [c for c in cards if c.get("action_category") != "top_avoid_move"]
        avoid = [c for c in cards if c.get("action_category") == "top_avoid_move"]
        columns = st.columns(2, gap="medium")
        for i, card in enumerate(positive):
            with columns[i % 2]:
                ui.decision_card(card)
        for card in avoid:
            ui.decision_card(card)
    if moves.empty:
        return
    ui.eyebrow("Move Rows")
    action_types = sorted(moves["action_type"].dropna().astype(str).unique())
    selected_types = st.multiselect(
        "Action type",
        action_types,
        key="move_recommendations_action_type_filter",
    )
    view = moves[moves["action_type"].isin(selected_types)] if selected_types else moves
    st.dataframe(view.head(100), use_container_width=True, hide_index=True)


def render_move_compare() -> None:
    """Render side-by-side move comparison."""
    team = selected_team()
    st.title("Move Compare")
    moves = team_frame(
        "reports/move_recommendations.parquet",
        REPORTS_DATA_DIR / "move_recommendations.parquet",
        "Move recommendations",
        _run_command(team),
    )
    if moves.empty:
        return
    labels = (
        moves["player_name"].fillna("Internal")
        + " - "
        + moves["action_type"].fillna("")
        + " - "
        + moves["recommendation"].fillna("")
    ).tolist()
    selected = st.multiselect(
        "Moves",
        labels,
        default=labels[:2],
        max_selections=4,
        key="move_compare_select",
    )
    if not selected:
        return
    view = moves.iloc[[labels.index(item) for item in selected]]
    st.dataframe(
        _cols(
            view,
            [
                "player_name",
                "action_type",
                "recommendation",
                "move_score",
                "roster_slot",
                "acquisition_path",
                "opportunity_cost_score",
                "why_do_this",
                "why_not_do_this",
                "confidence",
                "missing_data_flags",
            ],
        ),
        use_container_width=True,
        hide_index=True,
    )


def render_manual_review_queue() -> None:
    """Render manual review queue from rankings and action cards."""
    st.title(f"{team_name(selected_team())} — Manual Review Queue")
    rankings = rankings_frame()
    cards = pd.DataFrame(team_json("reports/action_cards.json", REPORTS_DATA_DIR / "action_cards.json") or [])
    if not cards.empty:
        review_cards = cards[
            cards["action_category"].astype(str).str.contains("manual", case=False)
        ]
        st.subheader("Manual Review Action")
        st.dataframe(review_cards, use_container_width=True, hide_index=True)
    if rankings.empty:
        return
    mask = rankings["manual_review_required"].fillna(False).astype(bool)
    mask |= rankings["missing_data_flags"].fillna("").astype(str).str.contains(
        "manual|stale|conflict|unknown|recent_transaction",
        case=False,
    )
    queue = rankings[mask]
    if queue.empty:
        st.success("No manual review rows in current artifacts.")
        return
    st.dataframe(
        _cols(
            queue,
            [
                "rank",
                "player_name",
                "candidate_type",
                "recommendation",
                "primary_roster_slot",
                "acquisition_path",
                "manual_review_required",
                "missing_data_flags",
                "evidence_summary",
            ],
        ),
        use_container_width=True,
        hide_index=True,
    )


def render_product_summary() -> None:
    """Render the product overview."""
    st.title("MoreyMachine")
    st.write(
        "MoreyMachine is an unofficial NBA roster-construction product that ranks "
        "potential 76ers acquisition targets by roster need, role, core fit, "
        "scenario usefulness, acquisition context, contract value, risk, and "
        "evidence quality."
    )
    rankings = rankings_frame()
    profiles = profiles_frame()
    cols = st.columns(4)
    cols[0].metric("V2 candidates", len(rankings))
    cols[1].metric(
        "Player profiles",
        len(profiles),
    )
    cols[2].metric(
        "Priority targets",
        int(
            (
                rankings.get("recommendation", pd.Series(dtype=str))
                == "Priority Target"
            ).sum()
        )
        if not rankings.empty
        else 0,
    )
    cols[3].metric(
        "Manual review",
        int(rankings.get("manual_review_required", pd.Series(dtype=bool)).sum())
        if not rankings.empty
        else 0,
    )
    st.subheader("How the product reasons")
    st.markdown(
        "The pipeline builds a roster world, compares Philadelphia to contender "
        "blueprints, identifies role-specific gaps, profiles each player's skills, "
        "checks compatibility with Embiid, Maxey, and George, simulates roster "
        "slots, evaluates acquisition feasibility, builds scenarios, then generates "
        "evidence-backed recommendations and clickable player profiles."
    )
    st.subheader("What refreshable real data means")
    st.markdown(
        f"The app reads cached artifacts only. To refresh, run `{REFRESH_COMMAND}` "
        "and the pipeline scripts; page loads do not call live APIs."
    )
    st.subheader("Current top board")
    render_board_table(rankings.head(20), include_profile_link=True)


def render_data_sources() -> None:
    """Render source, freshness, and artifact metadata."""
    st.title("Data Sources / Freshness")
    st.caption("Cached artifacts only; no live data fetches inside the app.")
    table = data_source_table()
    st.dataframe(table, use_container_width=True, hide_index=True)
    st.subheader("V2 product artifacts")
    artifacts = [
        CANDIDATE_FIT_RANKINGS_V2_PATH,
        PLAYER_PROFILES_PATH,
        EXPLANATION_CLAIMS_PATH,
        EVIDENCE_OBJECTS_PATH,
        ROSTER_WORLD_PATH,
        CONTENDER_BLUEPRINTS_PATH,
        GAP_MODEL_PATH,
        SKILL_PROFILES_PATH,
        COMPATIBILITY_PATH,
        ROSTER_SIMULATION_PATH,
        CANDIDATE_SCENARIOS_PATH,
        PLAYER_HELP_IMPACT_PATH,
        PLAYER_FIT_BREAKDOWNS_PATH,
        BEST_BY_NEED_PATH,
    ]
    rows = [_artifact_row(path) for path in artifacts]
    st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)


SLOT_LABELS = {
    "starting_center": "Starting Center",
    "backup_center": "Backup Center",
    "secondary_creator": "Guards / Creators",
    "movement_shooter": "Wings / Shooters",
    "defensive_forward": "Forwards / Defense",
    "regular_season_depth": "Depth / Development",
}
SLOT_ORDER = [
    "secondary_creator",
    "movement_shooter",
    "defensive_forward",
    "starting_center",
    "backup_center",
    "regular_season_depth",
]


def render_roster_lab() -> None:
    """Render the roster: depth chart, contention window, and composition.

    This is the planning surface a GM opens first — who is on the team, where
    they slot, and how the contention window looks against the core's ages.
    """
    team = selected_team()
    st.title(f"{team_name(team)} — Roster & Depth Chart")
    roster = team_frame(
        "features/roster_world.parquet",
        ROSTER_WORLD_PATH,
        "Current roster world",
        _run_command(team),
    )
    if roster.empty:
        return

    work = roster.copy()
    work["age_num"] = pd.to_numeric(work.get("age"), errors="coerce")
    work["min_num"] = pd.to_numeric(work.get("current_minutes"), errors="coerce").fillna(0)

    # --- Composition KPIs ---
    avg_age = work["age_num"].mean()
    weighted_age = (
        (work["age_num"] * work["min_num"]).sum() / work["min_num"].sum()
        if work["min_num"].sum()
        else avg_age
    )
    over_33 = int((work["age_num"] >= 33).sum())
    rotation = int((work["min_num"] >= 1000).sum())
    ui.scoreboard(
        [
            {"label": "Players", "value": len(work), "sub": "on roster world"},
            {"label": "Minutes-Weighted Age", "value": f"{weighted_age:.1f}" if pd.notna(weighted_age) else "—", "accent": "amber", "sub": "true team age"},
            {"label": "Rotation Bodies", "value": rotation, "accent": "green", "sub": "≥1000 min"},
            {"label": "Age 33+", "value": over_33, "accent": "red" if over_33 >= 3 else "slate", "sub": "window risk"},
        ]
    )

    # --- Contention window ---
    ui.eyebrow("Contention Window")
    _render_contention_window(work)

    # --- Depth chart whiteboard ---
    ui.eyebrow("Depth Chart by Role")
    _render_depth_chart(work)

    # --- Full roster detail ---
    ui.eyebrow("Roster Detail")
    cols = [
        "player_name",
        "position",
        "age",
        "current_role",
        "roster_slot",
        "usage_burden",
        "shooting_gravity",
        "defensive_role",
        "creation_role",
        "replaceability",
        "role_confidence",
        "missing_data_flags",
    ]
    st.dataframe(_cols(roster, cols), use_container_width=True, hide_index=True)
    narrative = text_artifact(REPORTS_DATA_DIR / "roster_world_phi.md")
    if narrative:
        with st.expander("Roster world narrative"):
            st.markdown(narrative)


def _select_core(work: pd.DataFrame) -> pd.DataFrame:
    """Identify the cornerstone players, not just whoever logs the most minutes.

    The roster pipeline marks franchise cornerstones with
    ``locked_role_status == "locked_core_role"`` (e.g. Embiid, Maxey, George),
    so those come first. If too few are flagged, fall back to the hardest
    players to replace, then to minutes load as a last resort.
    """
    usage_rank = {"primary_high": 3, "secondary": 2, "moderate": 1, "low": 0}
    ranked = work.copy()
    ranked["usage_rank"] = ranked.get("usage_burden", "").map(usage_rank).fillna(0)

    locked = ranked[ranked.get("locked_role_status", "") == "locked_core_role"]
    if len(locked) >= 2:
        core = locked
    else:
        irreplaceable = ranked[
            ranked.get("replaceability", "").isin(["not_replaceable", "hard_to_replace"])
        ]
        core = pd.concat([locked, irreplaceable]).drop_duplicates(subset="player_name")
        if len(core) < 2:
            core = ranked
    return core.sort_values(["usage_rank", "min_num"], ascending=False).head(4)


def _render_contention_window(work: pd.DataFrame) -> None:
    """Show the core's ages and a plain-language window read."""
    core = _select_core(work)
    cards = []
    for _, row in core.iterrows():
        age = row["age_num"]
        accent = "red" if pd.notna(age) and age >= 33 else ("amber" if pd.notna(age) and age >= 30 else "green")
        cards.append(
            {
                "label": "Cornerstone",
                "value": str(row.get("player_name")),
                "sub": f"age {int(age)} · {str(row.get('roster_slot','')).replace('_',' ')}" if pd.notna(age) else "age ?",
                "accent": accent,
            }
        )
    ui.scoreboard(cards)
    core_ages = core["age_num"].dropna()
    if not core_ages.empty:
        oldest_core = core_ages.max()
        core_avg = core_ages.mean()
        if oldest_core >= 35 or core_avg >= 31:
            verdict = (
                "Win-now window. A cornerstone is past his prime — value certainty and "
                "playoff readiness over long-term upside."
            )
        elif core_avg >= 28:
            verdict = (
                "Compressed window. Lean toward ready-now role players over multi-year "
                "development bets."
            )
        else:
            verdict = "Open window. There is room to add youth or take a longer view on fit."
        ui.note(f"<p><b>Window read.</b> {verdict} <span style='color:#5B6B7B;'>"
                f"Core avg age {core_avg:.1f}, oldest {int(oldest_core)}.</span></p>")


def _render_depth_chart(work: pd.DataFrame) -> None:
    """Render a whiteboard-style depth chart grouped by roster slot."""
    slots_present = [s for s in SLOT_ORDER if s in set(work["roster_slot"].dropna())]
    extras = [s for s in work["roster_slot"].dropna().unique() if s not in SLOT_ORDER]
    slots_present += list(extras)
    columns = st.columns(min(3, max(1, len(slots_present))))
    for i, slot in enumerate(slots_present):
        group = work[work["roster_slot"] == slot].sort_values("min_num", ascending=False)
        players = [
            {
                "name": r.get("player_name"),
                "age": r.get("age_num"),
                "mins": f"{int(r['min_num'])} min" if pd.notna(r["min_num"]) else "",
            }
            for _, r in group.iterrows()
        ]
        label = SLOT_LABELS.get(slot, str(slot).replace("_", " ").title())
        with columns[i % len(columns)]:
            ui.render(ui.depth_slot(label, len(players), players))


def render_blueprints() -> None:
    """Render contender blueprint outputs."""
    st.title("Contender Blueprint Explorer")
    blueprints = frame(
        CONTENDER_BLUEPRINTS_PATH,
        "Contender blueprints",
        "python scripts/build_contender_blueprints.py",
    )
    archetypes = frame(
        TEAM_ARCHETYPES_PATH,
        "Team construction archetypes",
        "python scripts/build_contender_blueprints.py",
    )
    if not blueprints.empty:
        selected = st.selectbox(
            "Blueprint",
            blueprints["blueprint_id"].astype(str).tolist(),
            key="contender_blueprint_select",
        )
        row = blueprints[blueprints["blueprint_id"].astype(str) == selected]
        st.dataframe(row.T, use_container_width=True)
    if not archetypes.empty:
        st.subheader("Team construction archetypes")
        st.dataframe(archetypes, use_container_width=True, hide_index=True)
    st.markdown(text_artifact(REPORTS_DATA_DIR / "contender_blueprints.md"))


def render_gap_model() -> None:
    """Render Sixers gap model."""
    team = selected_team()
    st.title(f"{team_name(team)} — Gap Priority Model")
    st.caption("Where the roster trails contender-level reference values, ranked by severity.")
    gaps = team_frame(
        "features/gap_model.parquet",
        GAP_MODEL_PATH,
        "Gap priority model",
        _run_command(team),
    )
    if gaps.empty:
        return
    category = st.multiselect(
        "Gap category",
        sorted(gaps["gap_category"].dropna().astype(str).unique()),
        key="gap_model_category_filter",
    )
    filtered = gaps
    if category:
        filtered = filtered[filtered["gap_category"].isin(category)]

    ranked = filtered.copy()
    ranked["severity_num"] = pd.to_numeric(ranked.get("severity"), errors="coerce").fillna(0)
    ranked = ranked.sort_values("severity_num", ascending=False)
    max_sev = max(float(ranked["severity_num"].max()) if not ranked.empty else 1.0, 1.0)

    ui.eyebrow("Severity Ranking")
    for _, row in ranked.iterrows():
        sev = float(row["severity_num"])
        ui.stat_bar(
            f"{row.get('gap_name', 'Gap')}  ·  {str(row.get('gap_category', '')).replace('_', ' ')}",
            sev,
            max_value=max_sev,
            kind=ui.severity_kind(sev, hi=max_sev * 0.66, mid=max_sev * 0.33),
            right=f"sev {sev:.0f}",
        )

    ui.eyebrow("Gap Detail")
    cols = [
        "gap_name",
        "gap_category",
        "severity",
        "confidence",
        "roster_slot_needed",
        "skill_requirements",
        "why_it_matters",
        "playoff_failure_mode",
        "what_fixes_it",
        "what_does_not_fix_it",
        "missing_data_flags",
    ]
    st.dataframe(_cols(ranked, cols), use_container_width=True, hide_index=True)
    narrative = text_artifact(REPORTS_DATA_DIR / "sixers_gap_model.md")
    if narrative:
        with st.expander("Gap model narrative"):
            st.markdown(narrative)


def render_skill_profiles() -> None:
    """Render player skill profiles and claim gates."""
    st.title("Player Skill Profiles")
    skills = frame(
        SKILL_PROFILES_PATH,
        "Player skill profiles",
        "python scripts/build_player_skill_profiles.py",
    )
    if skills.empty:
        return
    player = _player_select(skills, key_prefix="skill_profiles")
    row = skills[skills["player_name"] == player].head(1)
    st.dataframe(row.T, use_container_width=True)
    claim_cols = [col for col in skills.columns if col.endswith("_claim_allowed")]
    score_cols = [
        "player_name",
        "position",
        "current_team",
        "minutes",
        "spot_up_spacing",
        "movement_shooting",
        "secondary_creation",
        "connector_passing",
        "rim_protection",
        "wing_defense_proxy",
        "point_of_attack_defense_proxy",
        "defensive_rebounding",
        *claim_cols[:12],
        "missing_data_flags",
    ]
    st.subheader("Searchable skill table")
    st.dataframe(_cols(skills, score_cols), use_container_width=True, hide_index=True)


def render_compatibility() -> None:
    """Render player-to-player compatibility."""
    st.title("Player-to-Player Compatibility")
    compat = frame(
        COMPATIBILITY_PATH,
        "Candidate-core compatibility",
        "python scripts/build_compatibility_matrix.py",
    )
    if compat.empty:
        return
    player = _candidate_select(compat, "candidate_name", key_prefix="compatibility")
    filtered = compat[compat["candidate_name"] == player]
    core = filtered[
        filtered["sixers_player_name"].isin(
            ["Joel Embiid", "Tyrese Maxey", "Paul George"]
        )
    ]
    st.dataframe(core, use_container_width=True, hide_index=True)
    with st.expander("All current-roster compatibility rows"):
        st.dataframe(filtered, use_container_width=True, hide_index=True)


def render_roster_simulation() -> None:
    """Render roster slot and minutes simulation."""
    st.title("Roster Slot Simulation")
    simulation = frame(
        ROSTER_SIMULATION_PATH,
        "Roster simulation",
        "python scripts/simulate_roster_slots.py",
    )
    if simulation.empty:
        return
    player = _player_select(simulation, key_prefix="roster_simulation")
    st.dataframe(
        simulation[simulation["player_name"] == player].T,
        use_container_width=True,
    )
    cols = [
        "player_name",
        "primary_roster_slot",
        "possible_roster_slots",
        "blocked_slots",
        "expected_role_on_phi",
        "expected_minutes_context",
        "starter_possible",
        "closing_lineup_possible",
        "playoff_rotation_possible",
        "two_big_compatible",
        "no_clear_role",
        "contradiction_flags",
    ]
    st.dataframe(_cols(simulation, cols), use_container_width=True, hide_index=True)


def render_scenarios() -> None:
    """Render candidate scenarios."""
    st.title("Candidate Scenarios")
    scenarios = frame(
        CANDIDATE_SCENARIOS_PATH,
        "Candidate scenarios",
        "python scripts/build_candidate_scenarios.py",
    )
    if scenarios.empty:
        return
    player = _player_select(scenarios, key_prefix="candidate_scenarios")
    filtered = scenarios[scenarios["player_name"] == player]
    st.dataframe(filtered, use_container_width=True, hide_index=True)
    scenario_type = st.multiselect(
        "Scenario type",
        sorted(scenarios["scenario_type"].dropna().astype(str).unique()),
        key="candidate_scenarios_type_filter",
    )
    view = scenarios
    if scenario_type:
        view = view[view["scenario_type"].isin(scenario_type)]
    st.dataframe(view.head(200), use_container_width=True, hide_index=True)


def render_target_board() -> None:
    """Render segmented v2 target boards."""
    st.title("Target Board v2")
    rankings = rankings_frame()
    if rankings.empty:
        return
    tabs = st.tabs(
        [
            "Priority Targets",
            "Strong Fits If Affordable",
            "Role-Player Targets",
            "Only If Cheap",
            "Avoid",
            "Free Agents",
            "Trade Targets",
            "Minimum/MLE Candidates",
            "Backup Center Options",
            "Wing Defense Options",
            "Shooting Options",
            "Bench Creation Options",
            "Regular-Season Depth",
            "Unrealistic Watchlist",
            "Manual Review Needed",
        ]
    )
    tab_specs = [
        ("Priority Targets", rankings["recommendation"] == "Priority Target"),
        (
            "Strong Fits If Affordable",
            rankings["recommendation"] == "Strong Fit If Affordable",
        ),
        ("Role-Player Targets", rankings["recommendation"] == "Role-Player Target"),
        ("Only If Cheap", rankings["recommendation"] == "Only If Cheap"),
        ("Avoid", rankings["recommendation"] == "Avoid"),
        ("Free Agents", rankings["board_type"] == "free_agent"),
        ("Trade Targets", rankings["board_type"] == "trade_target"),
        (
            "Minimum/MLE Candidates",
            rankings["candidate_type"]
            .astype(str)
            .str.contains("minimum|mle", case=False),
        ),
        (
            "Backup Center Options",
            rankings["primary_roster_slot"].astype(str).str.contains("center|big"),
        ),
        (
            "Wing Defense Options",
            rankings["gaps_addressed"].astype(str).str.contains("Wing defense"),
        ),
        (
            "Shooting Options",
            rankings["gaps_addressed"]
            .astype(str)
            .str.contains("shooting|spacing", case=False),
        ),
        (
            "Bench Creation Options",
            rankings["gaps_addressed"].astype(str).str.contains("Bench creation"),
        ),
        (
            "Regular-Season Depth",
            rankings["primary_roster_slot"].astype(str).str.contains(
                "regular_season_depth"
            ),
        ),
        ("Unrealistic Watchlist", rankings["board_type"] == "watchlist"),
        ("Manual Review Needed", rankings["manual_review_required"]),
    ]
    for tab, (label, mask) in zip(tabs, tab_specs, strict=True):
        with tab:
            st.caption(_board_tab_caption(label))
            render_board_filters(
                rankings[mask],
                key_prefix=f"target_board_v2_{label}",
            )


def render_player_detail() -> None:
    """Render full player profile."""
    st.title("Player Detail v2")
    profiles = profiles_frame()
    if profiles.empty:
        return
    player = _player_select(profiles, key_prefix="player_detail")
    profile = profiles[profiles["player_name"] == player].iloc[0].to_dict()
    render_profile(profile)


def render_player_compare() -> None:
    """Render 2-4 player comparison."""
    st.title("Player Compare")
    profiles = profiles_frame()
    if profiles.empty:
        return
    names = profiles["player_name"].dropna().astype(str).sort_values().tolist()
    selected = st.multiselect(
        "Players",
        names,
        default=names[:2],
        max_selections=4,
        key="player_compare_players",
    )
    if not selected:
        return
    view = profiles[profiles["player_name"].isin(selected)]
    cols = [
        "player_name",
        "current_team",
        "position",
        "candidate_type",
        "recommendation",
        "final_fit_score",
        "primary_roster_slot",
        "expected_role_on_phi",
        "acquisition_path",
        "feasibility_tier",
        "top_gaps_helped",
        "gaps_not_helped",
        "fit_with_embiid",
        "fit_with_maxey",
        "fit_with_george",
        "main_concerns",
    ]
    st.dataframe(_cols(view, cols), use_container_width=True, hide_index=True)


def render_best_by_need() -> None:
    """Render best-by-need rankings."""
    team = selected_team()
    st.title("Best By Need")
    best = team_frame(
        "reports/best_by_need.parquet",
        BEST_BY_NEED_PATH,
        "Best by need",
        _run_command(team),
    )
    if best.empty:
        return
    need = st.selectbox(
        "Need",
        best["need_name"].astype(str).tolist(),
        key="best_by_need_select",
    )
    row = best[best["need_name"].astype(str) == need].iloc[0].to_dict()
    st.write(row.get("why_these_players_fit"))
    st.warning(row.get("what_to_watch_out_for"))
    for column in (
        "top_players",
        "realistic_only_top_players",
        "free_agent_top_players",
        "trade_target_top_players",
        "low_cost_top_players",
        "high_upside_top_players",
    ):
        st.subheader(column.replace("_", " ").title())
        st.dataframe(
            pd.DataFrame(_json_list(row.get(column))),
            use_container_width=True,
        )


def render_transaction_review() -> None:
    """Render stale-status and recent-transaction review rows."""
    st.title("Transaction Review")
    candidates = frame(
        CANDIDATE_UNIVERSE_PATH,
        "Candidate universe",
        "python scripts/build_candidate_universe.py --team PHI",
    )
    transactions = frame(
        TRANSACTIONS_PATH,
        "Recent transactions",
        "python scripts/refresh_transactions.py",
    )
    if not transactions.empty:
        st.subheader("Recent transaction feed")
        st.dataframe(transactions.head(200), use_container_width=True, hide_index=True)
    if candidates.empty:
        return
    status_cols = [
        "player_name",
        "candidate_type",
        "candidate_status_freshness",
        "salary_pulled_at",
        "missing_data_flags",
    ]
    mask = pd.Series(False, index=candidates.index)
    for column in ("candidate_status_freshness", "missing_data_flags"):
        if column in candidates.columns:
            mask = mask | candidates[column].fillna("").astype(str).str.contains(
                "stale|manual|conflict|recent_transaction", case=False
            )
    review = candidates[mask]
    if review.empty:
        st.success("No stale/manual-review candidate status rows in current artifacts.")
    else:
        st.dataframe(
            _cols(review, status_cols),
            use_container_width=True,
            hide_index=True,
        )


def render_reasoning_diagnostics() -> None:
    """Render validation and score diagnostics."""
    st.title("Reasoning Diagnostics")
    rankings = rankings_frame()
    if not rankings.empty:
        cols = st.columns(4)
        cols[0].metric("Rows", len(rankings))
        cols[1].metric(
            "Manual review",
            int(rankings["manual_review_required"].sum()),
        )
        cols[2].metric(
            "Priority targets",
            int((rankings["recommendation"] == "Priority Target").sum()),
        )
        cols[3].metric(
            "No-clear role",
            int((rankings["primary_roster_slot"] == "no_clear_role").sum()),
        )
        for column in (
            "final_recommendation_score",
            "risk_score",
            "acquisition_feasibility_score",
            "contract_value_score",
            "scenario_robustness_score",
        ):
            st.subheader(column.replace("_", " ").title())
            st.bar_chart(rankings[column].dropna())
    for path in (
        REASONING_VALIDATION_PATH,
        PROFILE_VALIDATION_PATH,
        SCHEMA_VALIDATION_PATH,
    ):
        st.subheader(path.name)
        text = text_artifact(path)
        st.markdown(text or f"`{path}` is missing.")


def render_backtest() -> None:
    """Render backtest proof and limits."""
    st.title("Backtest Proof")
    summary = text_artifact(BACKTEST_SUMMARY_PATH)
    if summary:
        st.markdown(summary)
    else:
        st.warning("Backtest summary missing.")
        st.code("python scripts/run_backtest.py", language="bash")
    data = json_artifact(
        BACKTEST_RESULTS_PATH,
        "Backtest results",
        "python scripts/run_backtest.py",
    )
    if data:
        st.json(data)


def render_limitations() -> None:
    """Render honest product limitations."""
    st.title("Limitations / Missing Data")
    st.markdown(
        "- Public contract data can lag or be incomplete.\n"
        "- Transaction status can go stale quickly during the offseason.\n"
        "- The model does not know private trade availability, medicals, or team "
        "intent.\n"
        "- Backtesting cannot perfectly reconstruct historical free-agent and trade "
        "availability.\n"
        "- A fit score is not a claim that the Sixers should acquire the player.\n"
        "- MoreyMachine is better at basketball-fit diagnosis than exact "
        "front-office feasibility."
    )
    profiles = profiles_frame()
    if not profiles.empty:
        missing = profiles[
            profiles["missing_data_flags"].fillna("none").astype(str) != "none"
        ]
        st.subheader("Profiles with missing/stale flags")
        st.dataframe(
            _cols(
                missing,
                [
                    "player_name",
                    "recommendation",
                    "profile_completeness",
                    "manual_review_required",
                    "missing_data_flags",
                    "missing_or_stale_data",
                ],
            ),
            use_container_width=True,
            hide_index=True,
        )


def rankings_frame() -> pd.DataFrame:
    """Load v2 rankings."""
    team = selected_team()
    return team_frame(
        "reports/candidate_fit_rankings_v2.parquet",
        CANDIDATE_FIT_RANKINGS_V2_PATH,
        "Candidate fit rankings v2",
        _run_command(team),
    )


def profiles_frame() -> pd.DataFrame:
    """Load player profiles."""
    team = selected_team()
    return team_frame(
        "reports/player_profiles.parquet",
        PLAYER_PROFILES_PATH,
        "Player profiles",
        _run_command(team),
    )


def render_board_filters(board: pd.DataFrame, key_prefix: str) -> None:
    """Render a filterable board table."""
    if board.empty:
        st.info("No players in this segment.")
        return
    prefix = _safe_widget_key(key_prefix)
    positions = sorted(board["position"].dropna().astype(str).unique())
    slots = sorted(board["primary_roster_slot"].dropna().astype(str).unique())
    selected_positions = st.multiselect(
        "Position",
        positions,
        key=f"{prefix}_position_filter",
    )
    selected_slots = st.multiselect(
        "Roster slot",
        slots,
        key=f"{prefix}_roster_slot_filter",
    )
    view = board
    if selected_positions:
        view = view[view["position"].isin(selected_positions)]
    if selected_slots:
        view = view[view["primary_roster_slot"].isin(selected_slots)]
    render_board_table(view.head(75), include_profile_link=True)


def render_board_table(board: pd.DataFrame, *, include_profile_link: bool) -> None:
    """Render board columns with optional profile id."""
    if board.empty:
        st.info("No rows available.")
        return
    view = _cols(board, BOARD_COLUMNS).copy()
    if include_profile_link:
        profiles = profiles_frame()
        if not profiles.empty:
            links = profiles[["player_id", "player_profile_id"]].drop_duplicates()
            if "player_id" in view.columns:
                view = view.merge(links, on="player_id", how="left")
    st.dataframe(view, use_container_width=True, hide_index=True)


def render_profile(profile: dict[str, Any]) -> None:
    """Render a full player profile from one profile row."""
    name = str(profile.get("player_name"))
    meta_bits = [
        str(profile.get("position", "")),
        f"age {int(profile['age'])}" if str(profile.get("age", "")).replace(".", "").isdigit() else "",
        str(profile.get("current_team", "")),
        str(profile.get("acquisition_path", "")).replace("_", " "),
    ]
    meta = " · ".join([bit for bit in meta_bits if bit])
    chips = ui.tier_chip(profile.get("recommendation"))
    if profile.get("recommendation_confidence"):
        chips += ui.chip(
            f"{profile.get('recommendation_confidence')} confidence",
            ui.confidence_kind(profile.get("recommendation_confidence")),
        )
    if profile.get("overall_tier"):
        chips += ui.chip(str(profile.get("overall_tier")), "neutral")
    ui.render(
        f'<div class="mm-band"><div><div class="team">{ui._h(name)}</div>'
        f'<div class="meta">{ui._h(meta)}</div></div>'
        f'<div class="band-right">{chips}</div></div>'
    )
    ui.scoreboard(
        [
            {"label": "Fit Score", "value": _fmt_num(profile.get("final_fit_score"))},
            {"label": "Roster Slot", "value": str(profile.get("primary_roster_slot", "—")).replace("_", " "), "accent": "slate"},
            {"label": "Feasibility", "value": _fmt_num(profile.get("acquisition_feasibility_score")), "accent": "amber"},
            {"label": "Scenario Robustness", "value": _fmt_num(profile.get("scenario_robustness_score")), "accent": "green"},
        ]
    )
    if profile.get("manual_review_required"):
        st.error("Manual review required before treating this as a recommendation.")

    st.markdown(profile.get("executive_summary") or "")
    sections = [
        ("Score Overview", _score_overview(profile)),
        ("What He Helps Most", profile.get("what_he_helps_most")),
        ("What He Does Not Solve", profile.get("what_he_does_not_solve")),
        ("Role on Sixers", profile.get("role_on_sixers")),
        ("Fit With Core", profile.get("fit_with_core_explanation")),
        ("Salary + Acquisition", profile.get("salary_and_acquisition_explanation")),
        ("Scenarios", _scenario_summary(profile)),
        ("Concerns", profile.get("main_concerns")),
        ("Why This Could Be Wrong", profile.get("why_this_could_be_wrong")),
        ("Recommendation Interpretation", profile.get("recommendation_interpretation")),
    ]
    for title, content in sections:
        st.subheader(title)
        st.write(content or "Not available.")

    st.subheader("Salary Card")
    st.json(_json_dict(profile.get("salary_card_json")))
    st.subheader("Evidence Table")
    evidence = _json_list(profile.get("evidence_objects"))
    st.dataframe(pd.DataFrame(evidence), use_container_width=True)
    st.subheader("Unsupported Claim Flags")
    st.write(_json_list(profile.get("unsupported_claim_flags")))
    with st.expander("Raw Profile Row"):
        st.json(_jsonable(profile))


def _score_overview(profile: dict[str, Any]) -> str:
    return (
        f"Tier: {profile.get('overall_tier')}; "
        f"slot: {profile.get('primary_roster_slot')}; "
        f"scenario robustness: {profile.get('scenario_robustness_score')}; "
        f"acquisition feasibility: {profile.get('acquisition_feasibility_score')}."
    )


def _scenario_summary(profile: dict[str, Any]) -> str:
    parts = []
    for key in (
        "best_case_scenario",
        "realistic_scenario",
        "downside_scenario",
        "playoff_scenario",
        "regular_season_scenario",
        "overpay_scenario",
        "missing_data_scenario",
    ):
        scenario = _json_dict(profile.get(key))
        if scenario:
            summary = scenario.get("upside_case") or scenario.get("downside_case")
            parts.append(f"{key}: {summary}")
    return "\n\n".join(parts)


def _sidebar_team_controls() -> None:
    """Render team, benchmark, and player controls."""
    available = sorted(set(load_available_teams()) | set(SUPPORTED_TEAM_ABBRS))
    current = selected_team()
    index = available.index(current) if current in available else available.index("PHI")
    team = st.sidebar.selectbox(
        "Selected team",
        available,
        index=index,
        key=SELECTED_TEAM_KEY,
    )
    st.sidebar.caption(team_name(team))
    comparison = team_frame(
        "reports/team_comparison.parquet",
        REPORTS_DATA_DIR / "team_comparison.parquet",
        "Team comparison",
        _run_command(team),
    )
    if not comparison.empty and "benchmark" in comparison.columns:
        benchmarks = comparison["benchmark"].dropna().astype(str).tolist()
        if benchmarks:
            st.sidebar.selectbox(
                "Benchmark",
                benchmarks,
                key=SELECTED_BENCHMARK_KEY,
            )
    rankings = rankings_frame()
    if not rankings.empty:
        names = rankings["player_name"].dropna().astype(str).sort_values().tolist()
        search = st.sidebar.selectbox(
            "Quick player search",
            [""] + names,
            key="sidebar_quick_player_search",
        )
        if search:
            match = rankings[rankings["player_name"].astype(str) == search].head(1)
            if not match.empty:
                st.session_state[SELECTED_PLAYER_ID_KEY] = int(match.iloc[0]["player_id"])
                st.sidebar.caption(f"Rank {int(match.iloc[0]['rank'])}: {search}")


def _run_command(team: str | None = None) -> str:
    """Return the exact team pipeline command."""
    normalized = normalize_team(team or selected_team())
    return (
        "export PYTHONPATH=src\n"
        f"python3 scripts/run_team_pipeline.py --team {normalized} --skip-refresh"
    )


def _team_artifact_status(team: str) -> list[dict[str, Any]]:
    """Return status rows for key team artifacts."""
    root = get_team_output_dir(team)
    artifacts = [
        "reports/team_level.json",
        "reports/team_comparison.parquet",
        "reports/action_cards.json",
        "reports/move_recommendations.parquet",
        "reports/candidate_fit_rankings_v2.parquet",
        "reports/player_profiles.parquet",
        "reports/best_by_need.parquet",
        "narratives/gm_executive_summary.md",
    ]
    return [
        {
            "artifact": artifact,
            "present": (root / artifact).exists(),
            "path": str(root / artifact),
        }
        for artifact in artifacts
    ]


def _sidebar_status() -> None:
    team = selected_team()
    required = _team_artifact_status(team)
    missing = [row["artifact"] for row in required if not row["present"]]
    if missing:
        st.sidebar.error("Missing team outputs")
        st.sidebar.caption(", ".join(missing[:4]))
        st.sidebar.code(_run_command(team), language="bash")
    else:
        st.sidebar.success("Team artifacts loaded")


def _artifact_row(path: Path) -> dict[str, Any]:
    metadata_path = Path(f"{path}.metadata.json")
    if metadata_path.exists():
        metadata = _json_dict(text_artifact(metadata_path))
    else:
        metadata = {}
    return {
        "artifact": path.name,
        "present": path.exists(),
        "rows": metadata.get("rows"),
        "columns": len(metadata.get("columns", [])),
        "created_at": metadata.get("created_at"),
        "run_id": metadata.get("run_id"),
        "data_mode": metadata.get("data_mode"),
        "source_files": ", ".join(metadata.get("source_files", [])[:3])
        if metadata
        else "",
        "path": str(path),
    }


def _player_select(frame_: pd.DataFrame, key_prefix: str) -> str:
    names = frame_["player_name"].dropna().astype(str).sort_values().unique().tolist()
    return st.selectbox("Player", names, key=f"{_safe_widget_key(key_prefix)}_player")


def _candidate_select(frame_: pd.DataFrame, column: str, key_prefix: str) -> str:
    names = frame_[column].dropna().astype(str).sort_values().unique().tolist()
    return st.selectbox(
        "Candidate",
        names,
        key=f"{_safe_widget_key(key_prefix)}_candidate",
    )


def _board_tab_caption(label: str) -> str:
    captions = {
        "Priority Targets": (
            "Strictest recommendation tier; requires role, scenario, and "
            "feasibility support."
        ),
        "Strong Fits If Affordable": (
            "Good basketball fit where price or availability controls the answer."
        ),
        "Role-Player Targets": "Useful role fits, not complete roster solutions.",
        "Only If Cheap": "Worth discussing only below the projected role cost.",
        "Avoid": "Bad role, weak evidence, or poor acquisition context.",
        "Free Agents": (
            "Free-agent-like status only; salary source and missing fields remain "
            "visible."
        ),
        "Trade Targets": (
            "Players with trade acquisition paths, including expensive trade context."
        ),
        "Unrealistic Watchlist": "Theoretical fit only; not recommendations.",
        "Manual Review Needed": (
            "Rows with stale, conflicting, or incomplete status/contract context."
        ),
    }
    return captions.get(label, "Segmented board view with full profile links.")


def _cols(frame_: pd.DataFrame, columns: list[str] | tuple[str, ...]) -> pd.DataFrame:
    return frame_.loc[:, [column for column in columns if column in frame_.columns]]


def _json_list(value: Any) -> list[Any]:
    if isinstance(value, list):
        return value
    if value in (None, "") or _is_na(value):
        return []
    try:
        parsed = json.loads(str(value))
    except (TypeError, json.JSONDecodeError):
        return [str(value)]
    return parsed if isinstance(parsed, list) else [parsed]


def _json_dict(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    if value in (None, "") or _is_na(value):
        return {}
    try:
        parsed = json.loads(str(value))
    except (TypeError, json.JSONDecodeError):
        return {}
    return parsed if isinstance(parsed, dict) else {}


def _jsonable(value: Any) -> Any:
    if isinstance(value, dict):
        return {key: _jsonable(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_jsonable(item) for item in value]
    if _is_na(value):
        return None
    return value


def _is_na(value: Any) -> bool:
    try:
        return bool(pd.isna(value))
    except (TypeError, ValueError):
        return False


if __name__ == "__main__":
    main()
