#!/usr/bin/env python
"""Audit entity resolution and write artifact lineage sidecars."""

from __future__ import annotations

from pathlib import Path

from moreymachine.data.entity_resolution import (
    build_player_identity_map,
    detect_duplicate_players,
)
from moreymachine.data.lineage import (
    discover_artifacts,
    new_run_id,
    write_metadata_for_artifact,
)
from moreymachine.utils.paths import DATA_DIR, PROJECT_ROOT, REPORTS_DATA_DIR

REPORT_PATH = REPORTS_DATA_DIR / "data_lineage_audit.md"


def main() -> int:
    """Build the lineage audit report and metadata sidecars."""
    run_id = new_run_id()
    identity_map, report = build_player_identity_map()
    duplicates = detect_duplicate_players(identity_map)

    artifacts = [
        path
        for path in discover_artifacts(DATA_DIR)
        if "demo" not in path.parts and "__pycache__" not in path.parts
    ]
    sidecars = []
    for artifact in artifacts:
        sidecars.append(
            write_metadata_for_artifact(
                artifact,
                run_id=run_id,
                source_files=(),
                upstream_artifacts=(),
                known_limitations=(
                    "Sidecar generated by lineage audit; upstream script-specific "
                    "metadata will replace generic values as builders are migrated.",
                ),
            )
        )

    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(
        _render_report(
            run_id=run_id,
            identity_rows=report.rows,
            resolved_players=report.resolved_players,
            duplicate_name_keys=report.duplicate_name_keys,
            unresolved_rows=report.unresolved_rows,
            artifacts=artifacts,
            sidecars=sidecars,
            duplicates=duplicates,
        )
    )
    print(f"Run ID: {run_id}")
    print(f"Resolved players: {report.resolved_players}")
    print(f"Duplicate normalized-name keys: {report.duplicate_name_keys}")
    print(f"Unresolved identity rows: {report.unresolved_rows}")
    print(f"Artifacts with metadata sidecars: {len(sidecars)}")
    print(f"Report: {REPORT_PATH}")
    return 0


def _render_report(
    *,
    run_id: str,
    identity_rows: int,
    resolved_players: int,
    duplicate_name_keys: int,
    unresolved_rows: int,
    artifacts: list[Path],
    sidecars: list[Path],
    duplicates,
) -> str:
    lines = [
        "# Data Lineage Audit",
        "",
        f"- Run ID: `{run_id}`",
        f"- Identity source rows: `{identity_rows}`",
        f"- Resolved canonical players: `{resolved_players}`",
        f"- Duplicate normalized-name keys: `{duplicate_name_keys}`",
        f"- Unresolved identity rows: `{unresolved_rows}`",
        f"- Artifacts discovered: `{len(artifacts)}`",
        f"- Metadata sidecars written: `{len(sidecars)}`",
        "",
        "## Duplicate Player Keys",
        "",
    ]
    if duplicates.empty:
        lines.append("No duplicate normalized-name keys with multiple player IDs.")
    else:
        lines.append("| normalized_name | player_name | distinct_ids | sources |")
        lines.append("| --- | --- | ---: | --- |")
        for row in duplicates.head(50).to_dict(orient="records"):
            lines.append(
                f"| {row.get('normalized_name', '')} | "
                f"{row.get('player_name', '')} | "
                f"{row.get('distinct_ids', '')} | {row.get('sources', '')} |"
            )
    lines.extend(
        [
            "",
            "## Artifact Metadata Sidecars",
            "",
            "| Artifact | Sidecar |",
            "| --- | --- |",
        ]
    )
    for artifact, sidecar in zip(artifacts, sidecars, strict=False):
        lines.append(f"| `{_display_path(artifact)}` | `{_display_path(sidecar)}` |")
    lines.extend(
        [
            "",
            "## Current Limitations",
            "",
            "- This audit can infer rows, columns, seasons, and data modes.",
            "- Script-specific upstream dependencies are generic until each builder "
            "writes its own metadata through `moreymachine.data.lineage`.",
            "- Entity resolution does not invent IDs for unresolved manual/status "
            "rows.",
        ]
    )
    return "\n".join(lines)


def _display_path(path: Path) -> str:
    try:
        return str(path.relative_to(PROJECT_ROOT))
    except ValueError:
        return str(path)


if __name__ == "__main__":
    raise SystemExit(main())
